---
namespace: ronmallory
name: win_docker
version: 1.0.0
readme: README.md
authors:
  - ronnymallory@gmail.com
description: install docker on windows host.
license:
  - GNU3.0
tags:
  - windows
  - docker
repository: https://github.com/RonMallory/ansible-collections
issues: https://github.com/RonMallory/ansible-collections/issues
