---
namespace: ronmallory
name: win_docker
version: 1.6.16.16.16.16.16.1EADME.md
authors:
  - ronnymallory@gmail.com
description: install docker on windows host.
license:
  - AGPL-3.0-or-later
tags:
  - windows
  - docker
repository: https://github.com/RonMallory/ansible-collections
issues: https://github.com/RonMallory/ansible-collections/issues
