---
# actions yaml for repo pipeline
name: CICD

on: [push, pull_request]

jobs:
  
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v2
  
  ansible-lint:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@master

      - name: ansible-lint
        uses: ansible/ansible-lint-action@master
        env:
          ACTION_PLAYBOOK_NAME: |
            "**/**/playbooks/*.yml"

  yamllint:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - name: 'Yamllint'
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_strict: false
...
