---
# actions to run on pull_request to publish to ansible-galaxy

name: publish

on: [pull_request]
  push:
    paths:
      - ./ronmallory/win_docker/*
      - ./ronmallory/win_docker/**/*
      - ./ronmallory/win_docker/**/**/*

jobs:

  publish_win_docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build and Deploy Collection
        uses: artis3n/ansible_galaxy_collection@v2
        with:
          api_key: '${{ secrets.GALAXY_API_KEY }}'
          collection_dir: './ronmallory/win_docker'
...
